-- MTec Estoque - Script de configuração do banco (Supabase / Postgres)
-- Versão: v2
-- Execute este arquivo no editor SQL do Supabase (projeto correto).
-- ATENÇÃO: este script APAGA e recria as tabelas usadas pelo sistema.

--------------------------------------------------------------------------------
-- LIMPAR ESTRUTURA ANTIGA (se existir)
--------------------------------------------------------------------------------

drop table if exists public.movimentos cascade;
drop table if exists public.materiais cascade;
drop table if exists public.configuracoes cascade;
drop table if exists public.usuarios cascade;

--------------------------------------------------------------------------------
-- TABELA: usuarios
--------------------------------------------------------------------------------

create table public.usuarios (
  id         bigint generated by default as identity primary key,
  username   text    not null unique,
  nome       text    not null,
  senha      text    not null,
  role       text    not null default 'usuario' check (role in ('admin','usuario')),
  created_at timestamptz not null default now()
);

comment on table public.usuarios is 'Usuários do sistema MTec Estoque';
comment on column public.usuarios.username is 'Login do usuário (único)';
comment on column public.usuarios.senha    is 'Senha hash simples gerada pela função hs() no app';
comment on column public.usuarios.role     is 'Perfil: admin ou usuario';

--------------------------------------------------------------------------------
-- TABELA: materiais
--------------------------------------------------------------------------------

create table public.materiais (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references public.usuarios(id) on delete cascade,
  codigo     text   not null unique,
  nome       text   not null,
  categoria  text   not null default 'Geral',
  unidade    text   not null default 'UN',
  qtd        numeric(18,3) not null default 0,
  minimo     numeric(18,3) not null default 0,
  valor      numeric(18,4) not null default 0,
  local      text,
  fornecedor text,
  obs        text,
  created_at timestamptz not null default now()
);

create index idx_materiais_user_id on public.materiais(user_id);
create index idx_materiais_nome    on public.materiais(nome);
create index idx_materiais_cat     on public.materiais(categoria);

comment on table public.materiais is 'Materiais/itens controlados por usuário (dono) no estoque';

--------------------------------------------------------------------------------
-- TABELA: movimentos
--------------------------------------------------------------------------------

create table public.movimentos (
  id            bigint generated by default as identity primary key,
  user_id       bigint references public.usuarios(id) on delete set null,
  tipo          text   not null check (tipo in ('entrada','saida')),
  material_id   bigint references public.materiais(id) on delete cascade,
  material_nome text   not null,
  qtd           numeric(18,3) not null,
  responsavel   text,
  obs           text,
  saldo         numeric(18,3),
  created_at    timestamptz not null default now()
);

create index idx_movimentos_user_created  on public.movimentos(user_id, created_at desc);
create index idx_movimentos_material      on public.movimentos(material_id);
create index idx_movimentos_tipo_created  on public.movimentos(tipo, created_at desc);

comment on table public.movimentos is 'Movimentações de estoque (entradas/saídas)';

--------------------------------------------------------------------------------
-- TABELA: configuracoes
--------------------------------------------------------------------------------

create table public.configuracoes (
  user_id bigint not null references public.usuarios(id) on delete cascade,
  chave   text   not null,
  valor   text   not null,
  created_at timestamptz not null default now(),
  primary key (user_id, chave)
);

comment on table public.configuracoes is 'Configurações por usuário (empresa, categorias extras, etc.)';

--------------------------------------------------------------------------------
-- DADOS INICIAIS
--------------------------------------------------------------------------------

-- Usuário administrador padrão:
--  username: administrador
--  senha: admin
--  (hash gerado pela função hs() do app = h1j67nz5)

insert into public.usuarios (username, nome, senha, role)
values ('administrador', 'Administrador MTec', 'h1j67nz5', 'admin')
on conflict (username) do nothing;

-- Usuário comum exemplo:
--  username: mtec
--  senha: mtec123
--  hash = hmo7bt97

insert into public.usuarios (username, nome, senha, role)
values ('mtec', 'Usuário Padrão', 'hmo7bt97', 'usuario')
on conflict (username) do nothing;

--------------------------------------------------------------------------------
-- RLS / POLÍTICAS (OPCIONAL)
-- Obs: por padrão, Supabase cria RLS habilitado. Se quiser liberar acesso
-- direto só pelo anon key, é possível desativar RLS nessas tabelas.
--------------------------------------------------------------------------------

-- Exemplo: desabilitar RLS (apenas se você controla o acesso só pelo anon key
-- e o banco for exclusivo deste app).
--
-- alter table public.usuarios      disable row level security;
-- alter table public.materiais     disable row level security;
-- alter table public.movimentos    disable row level security;
-- alter table public.configuracoes disable row level security;

-- Se preferir, crie políticas de RLS para filtrar por user_id com base no
-- JWT do Supabase. Como este app usa anon key simples, a forma mais direta
-- é manter RLS desabilitado para estas tabelas.

