-- ============================================================
-- MTEC Estoque 1.0 — Setup do banco de dados
-- Execute este arquivo no Supabase SQL Editor
-- ============================================================

-- 1. REMOVER tabelas antigas (se existirem)
drop table if exists public.movimentos   cascade;
drop table if exists public.materiais    cascade;
drop table if exists public.configuracoes cascade;
drop table if exists public.usuarios     cascade;
drop table if exists public.obras        cascade;

-- 2. TABELA OBRAS
create table public.obras (
  id          bigint generated by default as identity primary key,
  nome        text not null,
  descricao   text,
  created_at  timestamptz not null default now()
);

-- 3. TABELA MATERIAIS (isolado por obra)
create table public.materiais (
  id          bigint generated by default as identity primary key,
  obra_id     bigint not null references public.obras(id) on delete cascade,
  codigo      text,
  nome        text not null,
  categoria   text not null default 'Geral',
  unidade     text not null default 'UN',
  qtd         numeric not null default 0,
  minimo      numeric not null default 5,
  valor       numeric not null default 0,
  local       text,
  fornecedor  text,
  obs         text,
  created_at  timestamptz not null default now()
);

-- 4. TABELA MOVIMENTOS (isolado por obra)
create table public.movimentos (
  id             bigint generated by default as identity primary key,
  obra_id        bigint not null references public.obras(id) on delete cascade,
  tipo           text not null check (tipo in ('entrada','saida')),
  material_id    bigint references public.materiais(id) on delete set null,
  material_nome  text,
  qtd            numeric not null,
  responsavel    text,
  obs            text,
  saldo          numeric,
  created_at     timestamptz not null default now()
);

-- 5. TABELA CONFIGURACOES
--    obra_id = 0  → configurações globais da empresa
--    obra_id > 0  → configurações/categorias da obra
create table public.configuracoes (
  obra_id    bigint not null default 0,
  chave      text not null,
  valor      text not null,
  primary key (obra_id, chave)
);

-- 6. ÍNDICES para performance
create index on public.materiais (obra_id);
create index on public.movimentos (obra_id);
create index on public.movimentos (material_id);
create index on public.configuracoes (obra_id);

-- 7. RLS desabilitado (controle feito pelo app)
alter table public.obras          disable row level security;
alter table public.materiais      disable row level security;
alter table public.movimentos     disable row level security;
alter table public.configuracoes  disable row level security;

-- ============================================================
-- Pronto! Abra o app — na primeira abertura ele vai mostrar
-- o formulário de configuração inicial.
-- ============================================================
